from enum import Enum as enum


class Flavour(enum):
    CALABRESA = "CALABRESA"
    FRANGOCAT = "FRANGO C CATUPIRY"
    MARGHERITA = "MARGHERITA"
    BACON = "BACON"
    VEGETARIANA = "VEGETARIANA"
    PORTUGUESA = "PORTUGUESA"
    QQUEIJOS = "QUATRO QUEIJOS"
    PEPPERONI = "PEPPERONI"